- hosts: DockerNodes
  tasks:
    - name: Initialize Swarm Manager
      shell: docker swarm init --advertise-addr={{ ansible_default_ipv4.address }} | grep "docker swarm join --token"
      register: docker_swarm_join
      when: "inventory_hostname == 'swarm-manager'"
      tags:
        - docker-swarm
        - docker
    - name: Join Worker Nodes To Docker Swarm
      shell: "{{ hostvars['swarm-manager']['docker_swarm_join']['stdout'] }}"
      when: "inventory_hostname in groups['DockerWorkers']"
      tags:
        - docker-swarm
        - docker
